detections_file = "/Users/adare/data/capture3_left.csv"
first_frame = 300
last_frame = 600
tag_to_track = 1

initial_position_variance = 50
initial_rotation_variance = 50

# motion model
dt = 0.033           # video sample period [s]
sigma_velocity = 0.5 # in/s
sigma_omega = 0.1    # rad/s

# Measurement uncertainties [in], [rad]
dx = 0.2
dy = 0.2
dz = 0.2
drx = 0.2
dry = 0.2
drz = 0.2

# Tracking logic
max_num_coasts = 2
